version: "3.8"
services:
  db:
    container_name: nomadcities_db
    image: postgres:16
    restart: always
    volumes:
      - nomadcities-db-data:/var/lib/postgresql/data/pgdata
      - ./db/create-multiple-postgresql-databases.sh:/docker-entrypoint-initdb.d/create-multiple-postgresql-databases.sh
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    
  pgadmin:
    container_name: nomadcities_pgadmin
    image: dpage/pgadmin4
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "5050:5050"

  backend:
    container_name: nomadcities_backend
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - nomadcities_backend_images:/app/static
    build:
      context: ./backend
      args:
        INSTALL_DEV: ${INSTALL_DEV-false}
    ports:
      - "${EXTERNAL_BACKEND_PORT}:${INTERNAL_BACKEND_PORT}"

  frontend:
    container_name: nomadcities_frontend
    restart: always
    depends_on:
      - backend
    env_file:
      - .env
    build:
      context: ./frontend
    ports:
      - "4321:4321"

volumes:
  nomadcities-db-data:
  nomadcities_backend_images: